export enum AUTH_TYPE {
    OTHER_AUTH = 0,
    CHECK_RECOVERY_EMAIL,
    EMAIL_AUTH,
    EMAIL_SIGNUP,
    PHONE_AUTH,
    RECOVERY_PASSWORD,
    VERIFY_OTP,
    VERIFY_EMAIL,
    VERIFY_PASSWORD,
    VERIFY_SUCCESS,
    VERIFY_FAILED,
}